//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CirclesManagement.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationSetting
    {
        public int ID { get; set; }
        public int GradeNumerationTypeID { get; set; }
    
        public virtual GradeNumerationType GradeNumerationType { get; set; }
    }
}
