//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CirclesManagement.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson_Pupil
    {
        public int LessonID { get; set; }
        public int PupilID { get; set; }
        public bool WasInClass { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Pupil Pupil { get; set; }
    }
}
