//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CirclesManagement.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Timetable()
        {
            this.Lessons = new HashSet<Lesson>();
        }
    
        public int ID { get; set; }
        public int TeacherID { get; set; }
        public int ClassroomID { get; set; }
        public int CircleID { get; set; }
        public int WeekDayID { get; set; }
        public System.TimeSpan Time { get; set; }
    
        public virtual Circle Circle { get; set; }
        public virtual Classroom Classroom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lesson> Lessons { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual WeekDay WeekDay { get; set; }
    }
}
